version: '3'
services:
  vue:
    build: 
      context: ./rep_docker
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - vue-landing-network

  landing:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - vue-landing-network

networks:
  vue-landing-network:
    driver: bridge