# Usa la imagen base de NGINX
FROM nginx

# Copia los archivos de la página HTML estática al directorio de NGINX en el contenedor
COPY . /usr/share/nginx/html

# Exponer el puerto 80 para que pueda ser accedido desde fuera del contenedor
EXPOSE 80